steps:

 # ステップ2: Dockerイメージのビルド
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/rich-synapse-428706-s7/gke-demo-app', '.']

 # ステップ3: ビルドしたイメージをGoogle Container Registryにプッシュ
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/rich-synapse-428706-s7/gke-demo-app']